BEGIN TRY
    BEGIN TRY
        ALTER TABLE [$(FROM_DATABASE)].dbo.[$(TABLE_NAME)] DROP CONSTRAINT [$(TABLE_NAME)$PrimaryKey]
    END TRY BEGIN CATCH END CATCH;
    ALTER TABLE [$(FROM_DATABASE)].dbo.[$(TABLE_NAME)] DROP COLUMN [$(COL_NAME)];
END TRY BEGIN CATCH END CATCH;
GO