//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventorAccessPortal.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class All_Investigator
    {
        public int ID { get; set; }
        public Nullable<int> Project_Number { get; set; }
        public string Investigator { get; set; }
        public string DataSource { get; set; }
    
        public virtual Investigator Investigator1 { get; set; }
        public virtual Project_Number Project_Numbers { get; set; }
    }
}
