//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventorAccessPortal.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Combo_Family_Listing
    {
        public int ID { get; set; }
        public string Combo_Name { get; set; }
        public string Code { get; set; }
        public string DataSource { get; set; }
    
        public virtual Code Code1 { get; set; }
        public virtual Combo_Family Combo_Families { get; set; }
    }
}
