//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventorAccessPortal.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Investigator
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Investigator()
        {
            this.All_Investigators = new HashSet<All_Investigator>();
            this.Project_Numbers = new HashSet<Project_Number>();
        }
    
        public string Investigator_Name { get; set; }
        public string Organization { get; set; }
        public Nullable<int> Investigator_Number { get; set; }
        public string School_or_College { get; set; }
        public string Department_or_Unit { get; set; }
        public string Home_Address { get; set; }
        public string Phone_Number { get; set; }
        public string Email_Address { get; set; }
        public string Citizenship { get; set; }
        public string Gender { get; set; }
        public string DataSource { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<All_Investigator> All_Investigators { get; set; }
        public virtual College College { get; set; }
        public virtual Department Department { get; set; }
        public virtual Gender Gender1 { get; set; }
        public virtual Organization Organization1 { get; set; }
        public virtual Login_datum Login_Data { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project_Number> Project_Numbers { get; set; }
    }
}
