//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventorAccessPortal.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login_datum
    {
        public string Investigator_Name { get; set; }
        public string Username { get; set; }
        public string Salt { get; set; }
        public string Password { get; set; }
        public Nullable<bool> Suspended { get; set; }
        public Nullable<bool> Temp_Password { get; set; }
        public string DataSource { get; set; }
    
        public virtual Investigator Investigator { get; set; }
    }
}
