//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventorAccessPortal.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Transaction_ID { get; set; }
        public string File_Number { get; set; }
        public Nullable<System.DateTime> Transaction_Date { get; set; }
        public string Details { get; set; }
        public string Notes { get; set; }
        public string Code { get; set; }
        public Nullable<int> FY_Date { get; set; }
        public string DataSource { get; set; }
    
        public virtual Code Code1 { get; set; }
        public virtual File_Number File_Numbers { get; set; }
    }
}
