//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventorAccessPortal.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Web_Login_datum
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Web_Login_datum()
        {
            this.Web_Action_Data = new HashSet<Web_Action_datum>();
        }
    
        public string Investigator_Name { get; set; }
        public string Username { get; set; }
        public string Salt { get; set; }
        public string Password { get; set; }
        public Nullable<bool> Suspended { get; set; }
        public Nullable<bool> Temp_Password { get; set; }
        public string DataSource { get; set; }
        public bool Email_Confirmed { get; set; }
    
        public virtual Investigator Investigator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Web_Action_datum> Web_Action_Data { get; set; }
    }
}
